on: [push, pull_request]

name: Cargo Build

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        config:
          - node: ubuntu-latest
          - node: windows-latest
          - node: macos-latest
    runs-on: ${{ matrix.config.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-all-features
      - uses: actions-rs/cargo@v1
        with:
          command: build-all-features

      - uses: actions-rs/cargo@v1
        with:
          command: build-all-features

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --benches --features __bench